import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  NavBar,
  PrimaryButton,
  NavButton,
  PrimaryTitle,
  Info,
  InfoItem,
  Course,
  CourseSection,
  FormTextInput,
  LayoutContainer,
} from "../src/components/index";
import { ShieldLock, School } from "tabler-icons-react";
import {
  Container,
  Title,
  Group,
  useMantineTheme,
  List,
  Divider,
  Space,
  TextInput,
  PasswordInput,
  Card,
} from "@mantine/core";
import { useForm } from "@mantine/form";

const Admin: NextPage = () => {
  const theme = useMantineTheme();
  const form = useForm({
    initialValues: {
      email: "",
      password: "",
    },

    validate: {
      email: (value) =>
        /^\S+@\S+$/.test(value) ? null : "Ungültige Email Addresse",
      password: (value) =>
        value.length < 1 ? "Bitte geben sie ein Passwort ein" : null,
    },
  });
  return (
    <>
      <Head>
        <title>DRK Rostock Kurs Admin Anmeldung</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <Link href="/" passHref>
          <NavButton
            onClick={() => {}}
            leftIcon={<School size={24} strokeWidth={2} color={"white"} />}
          >
            Kurse
          </NavButton>
        </Link>
      </NavBar>
      <LayoutContainer>
        <header>
          <PrimaryTitle
            icon={
              <ShieldLock
                size={36}
                strokeWidth={2}
                color={theme.colors.red[6]}
              />
            }
            title={"Admin Authentifizierung"}
          />

          <Divider my="2rem" size="sm" />
        </header>
        <Card
          sx={(theme) => ({
            maxWidth: 500,
            margin: "auto",
          })}
          shadow="sm"
          p="lg"
        >
          <form onSubmit={form.onSubmit((values) => console.log(values))}>
            <FormTextInput
              label="Email"
              placeholder="Test@drk-rostock.de"
              input_recognizer={form.getInputProps("email")}
            />
            <Space h="1rem" />
            <PasswordInput
              required
              radius="sm"
              size="md"
              label="Password"
              placeholder="Password"
              {...form.getInputProps("password")}
            />
            <Space h="2rem" />
            <PrimaryButton
              color={"red"}
              compact={false}
              disabled={false}
              fullWidth={true}
              leftIcon={undefined}
              loading={false}
              size={"md"}
              uppercase={false}
              type={"submit"}
              variant={"filled"}
              onClick={() => {
                console.log(form.values);
              }}
            >
              Anmelden
            </PrimaryButton>
          </form>
        </Card>
      </LayoutContainer>
    </>
  );
};

export default Admin;
