import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  NavBar,
  PrimaryButton,
  NavButton,
  PrimaryTitle,
  Info,
  InfoItem,
  Course,
  CourseSection,
  SecondaryTitle,
} from "../../src/components/index";
import {
  ShieldLock,
  School,
  Users,
  CalendarEvent,
  Trash,
} from "tabler-icons-react";
import {
  Container,
  Title,
  Group,
  useMantineTheme,
  List,
  Divider,
  Space,
  TextInput,
  PasswordInput,
  Card,
  Table,
} from "@mantine/core";
import { useForm } from "@mantine/form";

const Teilnehmer: NextPage = () => {
  const theme = useMantineTheme();
  const form = useForm({
    initialValues: {
      name: "",
      vorname: "",
      bereich: "",
      kostenstelle: "",
    },
  });
  return (
    <>
      <Head>
        <title>DRK Rostock Kurs Teilnehmer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar>
        <Link href="/" passHref>
          <NavButton
            onClick={() => {}}
            leftIcon={<School size={24} strokeWidth={2} color={"white"} />}
          >
            Kurse
          </NavButton>
        </Link>
      </NavBar>
      <Container
        sx={(theme) => ({
          backgroundColor: theme.colors.primary[0],
        })}
        px="2rem"
        py="1rem"
        fluid={true}
      >
        <Container size="lg" py="2rem">
          <header>
            <PrimaryTitle
              icon={
                <ShieldLock
                  size={36}
                  strokeWidth={2}
                  color={theme.colors.red[6]}
                />
              }
              title={"Kurs Teilnehmer"}
            />

            <Divider my="2rem" size="sm" />
          </header>

          <Info sx={() => ({})} spacing={0} type="unordered" size="xl">
            <Group position="center" align="center">
              <InfoItem
                icon={
                  <School
                    size={24}
                    strokeWidth={2}
                    color={theme.colors.red[6]}
                  />
                }
              >
                Excel Grundlagen
              </InfoItem>
              <InfoItem
                icon={
                  <CalendarEvent
                    size={24}
                    strokeWidth={2}
                    color={theme.colors.red[6]}
                  />
                }
              >
                Datum: 11.03.2022
              </InfoItem>
              <InfoItem
                icon={
                  <Users
                    size={24}
                    strokeWidth={2}
                    color={theme.colors.red[6]}
                  />
                }
              >
                Teilnehmer: 1/10
              </InfoItem>
            </Group>
          </Info>
          <Space h="2rem" />
          <Card shadow="sm" p="lg">
            <Table>
              <thead>
                <tr>
                  <th>Name</th>
                  <th>Vorname</th>
                  <th>Bereich</th>
                  <th>Kostenstelle</th>
                  <th>Optionen</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Klingbeil</td>
                  <td>Jan</td>
                  <td>KiJu</td>
                  <td>533232</td>
                  <td>
                    <PrimaryButton
                      color={"red"}
                      compact={false}
                      disabled={false}
                      fullWidth={false}
                      leftIcon={<Trash />}
                      loading={false}
                      size={"sm"}
                      uppercase={false}
                      type={"button"}
                      variant={"outline"}
                      onClick={() => {}}
                    >
                      Löschen
                    </PrimaryButton>
                  </td>
                </tr>
              </tbody>
            </Table>
          </Card>
        </Container>
      </Container>
    </>
  );
};

export default Teilnehmer;
